#! /bin/sh

# Autostart
sxhkd &
picom &
mpd &
sh ~/.fehbg &
sh ~/.config/polybar/launch.sh 

# Workspaces
bspc monitor -d 1 2 3 4 5

bsp-layout set tall 1 -- --master-size 0.5

# Bspc Configs
bspc config border_width	1
bspc config normal_border_color \#689d6a
bspc config active_border_color \#689d6a
bspc config focused_border_color \#98971a

bspc config window_gap		14
bspc config split_ratio		0.50
